# Frontend Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      name: front-pod
      labels:
        app: front
    spec:
      containers:
      - name: front-con
        image: yunchae02/front:1

---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80   
  type: LoadBalancer  

# Backend Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      name: back-pod
      labels:
        app: back
    spec:
      containers:
      - name: back-con
        image: yunchae02/back:1

